aemsites/hubblehomes-com

helix-query.yaml
Fix #37
Test URLs:
- After: https://issue-37--hubblehomes-com--aemsites.hlx.live/
=> add inventory home query index

helix-query.yaml
Fix #<gh-issue-id>
Test URLs:
- After: https://issue-7--hubblehomes-com--aemsites.hlx.live/
=> fix helix query for inventory homes

helix-query.yaml
Fix #37 
Test URLs:
- After: https://issue-37--hubblehomes-com--aemsites.hlx.live/
=> use correct paths in helix query

blocks/footer/footer.js, blocks/header/header.css, blocks/header/header.js, scripts/delayed.js
Added livechat functionality 
Fix #45
Test URLs:
Before: https://main--hubblehomes-com--aemsites.hlx.live/drafts/dfink/blank-test-page
After: https://45-livechat--hubblehomes-com--aemsites.hlx.live/drafts/dfink/blank-test-page
=> Adding Live Chat

blocks/models/cards/FeaturedCard.js, scripts/models.js, styles/styles.css, templates/community/community.js
Add featured plans to the community page
Fix #[77](https://github.com/aemsites/hubblehomes-com/compare/issue-77)
Test URLs:
- After: https://issue-77--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/nampa/adams-ridge
=> Add featured plans to the community page

blocks/header/header.css, blocks/models/cards/BaseCard.js, blocks/models/cards/CommunityCard.js, blocks/models/cards/FeaturedCard.js, blocks/models/cards/HomePlansCard.js, blocks/models/cards/InventoryCard.js, blocks/models/cards/card.css, scripts/inventory.js, scripts/mortgage.js, templates/community/community.js
* update style of image. with rounded corners
* provide a calculation function for the rate
Fix #[80](https://github.com/aemsites/hubblehomes-com/issues/80)
Test URLs:
- After: https://issue-80--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/nampa/adams-ridge
=> [Cards] - Update card designs for simplicity

blocks/promotion/promotion.js, blocks/subnav/subnav.js, scripts/aem.js, styles/layouts.css, templates/blocks/cards/FeaturedCard.js, templates/blocks/cards/HomePlansCard.js, templates/blocks/cards/InventoryCard.js, templates/communities/communities.css, templates/communities/communities.js
Fix #[92](https://github.com/aemsites/hubblehomes-com/issues/92)
Test URLs:
- After: https://issue-92--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/nampa/adams-ridge
=> Fixing CLS for communities

blocks/subnav/subnav.css
Fix #96 
Test URLs:
- After: https://issue-96--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/nampa/adams-ridge
=> updates for sub nav button styles

blocks/promotion/promotion.js, blocks/subnav/subnav.js, scripts/aem.js
Fix #98 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.page/about-us
- After: https://issue-98--hubblehomes-com--aemsites.hlx.page/about-us
Before
After
=> removing button styles

icons/email.svg, icons/phone.svg, scripts/sales-center.js, scripts/svg-helper.js, templates/blocks/specialists/specialists.css, templates/communities/communities.css, templates/communities/communities.js, templates/inventory/inventory.js
Fix #100 
Test URLs:
- After: https://issue-100--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/nampa/adams-ridge
=> [Communities Template] - add office information #100

blocks/subnav/subnav.css, scripts/inventory.js, styles/layouts.css, templates/blocks/actionbar/actionbar.css, templates/communities/communities.css, templates/communities/communities.js
Fix #108 
Test URLs:
- After: https://issue-108--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/nampa/adams-ridge
=> [Inventory Page] - hardening for missing content #108

blocks/subnav/subnav.js, scripts/communities.js, scripts/inventory.js, scripts/models.js, scripts/mortgage.js, scripts/sales-center.js, scripts/workbook.js, templates/communities/communities.js, templates/inventory/inventory.js
Fix #114 
Test URLs:
- After: https://issue-114--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/nampa/adams-ridge
=> [Performance] - provide an API around loading the worksheet data #114

scripts/workbook.js
=> Fix single sheet issue with workbook.js

helix-query.yaml
Fixing format for publisheddate
=> Update helix-query.yaml for news published date

templates/default/default.css
Fix #134 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.page/about-us
- After: https://issue-134--hubblehomes-com--aemsites.hlx.page/about-us
=> Fixing padding

templates/news-landing/news-landing.js
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.page/
- After: https://formatting--hubblehomes-com--aemsites.hlx.page/news
=> page layout changes

scripts/breadcrumbs.js, styles/styles.css, templates/communities/communities.js
Fix #131 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/nampa/covey-run
- After: https://issue-131--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/nampa/covey-run
Non Existent communities (user is redirected up)
https://main--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/boise/charlesworth
https://issue-131--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/boise/charlesworth
* fix breadcrumb element nesting
=> Handle sold out communities and non existent communities

blocks/columns/columns.css, blocks/columns/columns.js, icons/angle-right-black.svg, icons/angle-right-white.svg, styles/fonts.css
Fix #71 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/about-us
- After: https://issue-71--hubblehomes-com--aemsites.hlx.live/about-us
=> mobile accordion for about

blocks/columns/columns.css, blocks/columns/columns.js
Fix #155 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/about-us
- After: https://issue-155--hubblehomes-com--aemsites.hlx.live/about-us
=> fix about us page styling

scripts/communities.js, scripts/inventory.js, templates/communities/communities.js
Fix #160 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/new-homes/idaho/boise-metro/nampa/adams-ridge
- After: https://issue-160--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/nampa/adams-ridge
=> Extend filtering capabilities

blocks/carousel/carousel.js
fixing carousel issue when it is single with no content
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/caldwell
- After: https://carousel-fix--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/caldwell
=> Carousel Issue Fix

scripts/communities.js, scripts/inventory.js, styles/styles.css, templates/blocks/cards/BaseCard.js, templates/blocks/cards/Card.js, templates/blocks/cards/CardFactory.js, templates/blocks/cards/CommunityCard.js, templates/blocks/cards/cards.css, templates/communities/communities.js, templates/home-plan/home-plan.js, templates/inventory/inventory.js, templates/locations/locations.css, templates/locations/locations.js, templates/model/model.js
Fix #150 
Test URLs:
- After: https://issue-150--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/nampa
https://issue-150--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro
https://issue-150--hubblehomes-com--aemsites.hlx.page/new-homes/idaho
=> [Template] Communities Landing Page

templates/news-detail/news-detail.css, templates/news-detail/news-detail.js, templates/news-landing/news-landing.css
Fix #179 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/news/news-detail/building-a-greener-future-hubble-homes-receives-2024-energy-star-market-leader-award-161
- After: https://issue-179--hubblehomes-com--aemsites.hlx.page/news/news-detail/building-a-greener-future-hubble-homes-receives-2024-energy-star-market-leader-award-161
* Fixing image size
* Tightening up recent news article listing
=> [Recent News] - Images are distorted

blocks/header/header.css
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.page/
- After: https://nav-rollback--hubblehomes-com--aemsites.hlx.page/
=> Rolling back spacing in nav

blocks/carousel/carousel.css, blocks/header/header.css
Fix #192 
Test URLs:
- After: https://issue-192--hubblehomes-com--aemsites.hlx.page/
=> Simplify navigation menus and styling

scripts/communities.js, scripts/currency-formatter.js, templates/blocks/cards/FeaturedCard.js
Fix #195 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/caldwell
- After: https://issue-195--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/caldwell
vs
=> Don't expect a space before or after the - range.

styles/styles.css
Fix #199 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.page/new-homes/idaho
- After: https://issue-199--hubblehomes-com--aemsites.hlx.page/new-homes/idaho
=> Fix grey bar padding

blocks/carousel/carousel.css, blocks/carousel/carousel.js, blocks/header/header.css, fstab.yaml, icons/gallery.svg, scripts/gallery.js, styles/gallery.css
Fix #126 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/home-plans/plan-detail/agate
- After: https://issue-126--hubblehomes-com--aemsites.hlx.live/home-plans/plan-detail/agate
=> Create Image Gallery

.github/pull_request_template.md, scripts/scripts.js
Fix #175 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.page/
- After: https://issue-175--hubblehomes-com--aemsites.hlx.page/
=> Flip to woodside homes spreadsheet

blocks/carousel/carousel.js
Fix #203 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.page/home-plans/plan-detail/agate#gallery
- After: https://issue-203--hubblehomes-com--aemsites.hlx.page/home-plans/plan-detail/agate#gallery
=> Remove the second title

blocks/carousel/carousel.css, blocks/tabs/tabs.css, styles/styles.css, templates/energy/energy.css, templates/energy/energy.js
Fix #202 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.page/energy
- After: https://issue-202--hubblehomes-com--aemsites.hlx.page/energy
=> Create energy page

blocks/banner/banner.css, blocks/banner/banner.js, blocks/cards/cards.css, styles/index.css, styles/styles.css
Fix #189 
Test URLs:
- After: https://issue-189--hubblehomes-com--aemsites.hlx.page/
Ditch the form from the banner 
Try to break apart the page styles out from the block styles.
=> banner clean up and card style clean up

blocks/carousel/carousel.js, blocks/carousel/gallery.js
There are variants of how the slide show can be created, we now support the following.
Heart-of-Hubble:
Caldwell:
Mason Creek:
Fix #191 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.page/heart-of-hubble
- After: https://issue-191--hubblehomes-com--aemsites.hlx.page/heart-of-hubble
- Before: https://main--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/caldwell
- After: https://issue-191--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/caldwell
- Before: https://main--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/caldwell/mason-creek
- After: https://issue-191--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/caldwell/mason-creek
=> Support different scenarios

blocks/footer/footer.css, blocks/footer/footer.js, blocks/header/header.css, blocks/header/header.js, scripts/search-helper.js, scripts/workbook.js, styles/styles.css, templates/sales-team/sales-team.js
* search home plans
* search cities
* handle navigation with keyboard
* deep link into sales team page with agent result
* fix issue with undefined when selecting a community
Fix #171 
FIx #146
Test URLs:
- After: https://issue-171--hubblehomes-com--aemsites.hlx.page/
=> Fix search results (undefined) and update navigation for results

templates/about-us/about-us.css
Fix #236 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.page/about-us
- After: https://issue-236--hubblehomes-com--aemsites.hlx.page/about-us
=> issue-236: Fix request info button on about us page

blocks/carousel/carousel-touch.js, blocks/carousel/carousel.css, blocks/carousel/carousel.js, blocks/carousel/gallery.css, blocks/carousel/gallery.js, blocks/top-banner/top-banner.css, blocks/top-banner/top-banner.js, scripts/gallery.js, styles/buttons.css, styles/styles.css
* working on styles
* adding title bar for gallery and gallery overlay
Fix #239 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/caldwell/brittany-heights-at-windsor-creek
- After: https://issue-239--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/caldwell/brittany-heights-at-windsor-creek
=> Gallery changes

blocks/heading/heading.css, templates/communities/communities.js, templates/promotion/promotion.css, templates/promotion/promotion.js
Fix #234 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/promotions/promotions-detail/your-way-savings
- After: https://issue-234--hubblehomes-com--aemsites.hlx.live/promotions/promotions-detail/your-way-savings
=> Promotion Page

blocks/carousel/gallery.js, scripts/gallery.js
Fix #222 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/new-homes/idaho/boise-metro/star/greendale-grove
- After: https://issue-222--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/star/greendale-grove
Open the gallery, then dismiss the banner.  The gallery should reposition itself.
=> Fix resize issue when banner is dismissed.

blocks/promotion-details/promotion-details.css, blocks/promotion-details/promotion-details.js, styles/buttons.css
Fix #<gh-issue-id>
Test URLs:
- After: https://issue-128--hubblehomes-com--aemsites.hlx.page/
=> Fetch Latest

blocks/carousel/carousel.css, templates/promotion/promotion.css
Fix #250, #251 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/promotions/promotions-detail/hubble-homes-for-heroes
- After: https://issue-250--hubblehomes-com--aemsites.hlx.live/promotions/promotions-detail/hubble-homes-for-heroes
=> Remove Arrow from Carousel CTA & add CSS changes for promotion.css

blocks/carousel/carousel-touch.js, blocks/carousel/gallery.css, blocks/header/header.js, blocks/image-gallery/image-gallery.css, blocks/image-gallery/image-gallery.js, scripts/sales-center.js, scripts/scripts.js, scripts/workbook.js, styles/buttons.css, styles/styles.css, templates/inspiration-gallery/inspiration-gallery.css, templates/inspiration-gallery/inspiration-gallery.js
Fix #127
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.page/inspiration-gallery
- After: https://issue-127--hubblehomes-com--aemsites.hlx.page/inspiration-gallery
=> Inspiration gallery

scripts/article-list.js
Fix #260 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.page/news
- After: https://issue-260--hubblehomes-com--aemsites.hlx.page/news
=> Category Filter on news page occasionally not working

blocks/carousel/carousel-touch.js, blocks/carousel/carousel.js, blocks/carousel/gallery-init.js, blocks/carousel/gallery.css, blocks/carousel/gallery.js, blocks/header/header.css, blocks/image-gallery/image-gallery.css, blocks/image-gallery/image-gallery.js, blocks/top-banner/top-banner.css, blocks/top-banner/top-banner.js, scripts/aem.js, scripts/gallery-rules.js, scripts/gallery.js, scripts/scripts.js, scripts/workbook.js, styles/styles.css, templates/blocks/breadcrumbs/breadcrumbs.css, templates/blocks/breadcrumbs/breadcrumbs.js, templates/inspiration-gallery/inspiration-gallery.css, templates/inventory/inventory.css
Fix #267
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/middleton/waterford/maple-loft/550-limerick-ct/999
- After: https://issue-267--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/middleton/waterford/maple-loft/550-limerick-ct/999
To test, you will need to duplicate elements in the accordion to fill it.
It should look like this with two extra cards added:
=> Fix sizing for cards in the accordion

blocks/embed/embed.js, scripts/aem.js, scripts/delayed.js, scripts/forms-helper.js, scripts/hubspot-helper.js, scripts/live-chat-helper.js, templates/news-detail/news-detail.js
Fix #265., #138 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/news/news-detail/were-still-here-for-you-during-covid19-13
- After: https://issue-265--hubblehomes-com--aemsites.hlx.page/news/news-detail/were-still-here-for-you-during-covid19-13
=> fix#265, 138

tools/sidekick/library.html
Test URLs:
- After: https://library-html--hubblehomes-com--aemsites.hlx.page/
=> Add library template

helix-query.yaml
Fix #181 
Test URLs:
- After: https://issue-181--hubblehomes-com--aemsites.hlx.page/
=> Add a default query index

blocks/carousel/carousel.js, blocks/carousel/gallery-init.js, blocks/carousel/gallery.css, blocks/carousel/gallery.js, scripts/gallery-rules.js, templates/home-plan/home-plan.css, tools/sidekick/library.html
Fix #275 
Test URLs:
- After: https://issue-275--hubblehomes-com--aemsites.hlx.page/
=> Gallery rendering requires H2 and H3 headings.

blocks/cards/cards.css, blocks/top-banner/top-banner.css
Fix #286 
Test URLs:
- After: https://issue-286--hubblehomes-com--aemsites.hlx.page/
This also fixes an issue for banner in library
=> fix button effect when hovering over the cards

blocks/tabs/tabs.css
Fix #<gh-issue-id>
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/new-homes/idaho/boise-metro/caldwell/mason-creek/ridenbaugh/10881-sky-dive-st/999
- After: https://issue-293--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/caldwell/mason-creek/ridenbaugh/10881-sky-dive-st/999
=> Center floorplan image

blocks/carousel/gallery-init.js, blocks/carousel/gallery.css
Fix #290 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/new-homes/idaho/boise-metro/caldwell/mason-creek/ridenbaugh/10881-sky-dive-st/999
- After: https://issue-290--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/caldwell/mason-creek/ridenbaugh/10881-sky-dive-st/999
=> Fix gallery header not appearing

templates/inventory-list/inventory-list.css, templates/inventory-list/inventory-list.js
Fix #287 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/inventory
- After: https://issue-287-2--hubblehomes-com--aemsites.hlx.live/inventory
=> adding limit check

templates/home-plans/home-plans.css, templates/home-plans/home-plans.js
Fix #329 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/home-plans
- After: https://issue-329--hubblehomes-com--aemsites.hlx.live/home-plans
=> Introduce townhomes to home plans page

blocks/carousel/gallery-init.js, blocks/carousel/gallery.css, blocks/image-gallery/image-gallery.css, scripts/gallery-rules.js, styles/styles.css
Fix #306 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/new-homes/idaho/boise-metro/nampa/adams-ridge/agate
- After: https://issue-306--hubblehomes-com--aemsites.hlx.live/new-homes/idaho/boise-metro/nampa/adams-ridge/agate
=> Fixing double scrollbars and gallery not rendering correctly the second time

blocks/embed/embed.css
Fix #<gh-issue-id>
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.page/contact-us
- After: https://update-forms--hubblehomes-com--aemsites.hlx.page/contact-us
=> Update form styling to remove width requirements

templates/blocks/cards/CommunityCard.js, templates/communities/communities.js
Fix #344 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/new-homes/idaho/boise-metro/caldwell/mason-creek
- After: https://issue-344--hubblehomes-com--aemsites.hlx.live/new-homes/idaho/boise-metro/caldwell/mason-creek
=> Directions CTA on "Featured Plans" cards and community numbers

icons/directions.svg, templates/communities/communities.css, templates/communities/communities.js
Fix #357
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/new-homes/idaho/boise-metro/star/sellwood
- After: https://issue-357--hubblehomes-com--aemsites.hlx.live/new-homes/idaho/boise-metro/star/sellwood
=> Fix layout for firefox

templates/home-plans/home-plans.js
Fix #360
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/home-plans
- After: https://issue-360--hubblehomes-com--aemsites.hlx.live/home-plans
=> Sort by price ascending

blocks/embed/embed.js
Fix #362 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/promotions/promotions-detail/3-2-1-buydown
- After: https://issue-362--hubblehomes-com--aemsites.hlx.live/promotions/promotions-detail/3-2-1-buydown
- Before: https://main--hubblehomes-com--aemsites.hlx.live/warranty
- After: https://issue-362--hubblehomes-com--aemsites.hlx.live/warranty
- Before: https://main--hubblehomes-com--aemsites.hlx.live/contact-us
- After: https://issue-362--hubblehomes-com--aemsites.hlx.live/contact-us
=> Form not rendering using embed block

scripts/inventory.js, scripts/models.js, templates/blocks/cards/FeaturedCard.js
* featured cards should show community phone number
Fix #364
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/new-homes/idaho/boise-metro/kuna/sera-sole
- After: https://issue-364--hubblehomes-com--aemsites.hlx.live/new-homes/idaho/boise-metro/kuna/sera-sole
=> New community with no inventory throws error

templates/home-plan/home-plan.js, templates/inventory/inventory.js, templates/model/model.js
Fix #366 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/new-homes/idaho/boise-metro/meridian/canyons-at-prescott-ridge/charlotte/6235-w-fireline-st/999
- After: https://issue-366--hubblehomes-com--aemsites.hlx.live/new-homes/idaho/boise-metro/meridian/canyons-at-prescott-ridge/charlotte/6235-w-fireline-st/999
=> Fix layout in accordion rendering

templates/home-plan/home-plan.css
Fix #373 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.aem.live/home-plans/plan-detail/monarch
- After: https://home-plans--hubblehomes-com--aemsites.aem.live/home-plans/plan-detail/monarch
=> Home plan title fix

.github/pull_request_template.md, README.md, blocks/footer/footer.js, blocks/top-banner/top-banner.css, blocks/top-banner/top-banner.js, templates/promotion/promotion.js
Fix #377, #380 
Test URLs:
- After: https://issue-377--hubblehomes-com--aemsites.hlx.page/
=> Top banner no-links usecase

blocks/columns/columns.css, blocks/description/description.css, styles/styles.css
Fix #384 
Test URLs:
- Before: https://main--hubblehomes-com--aemsites.aem.page/why-hubble
- After: https://padding-fix--hubblehomes-com--aemsites.aem.page/why-hubble
=> Padding fix
